function Mifigurad3(X1, Y1, Z1)
%CREATEFIGURE(X1, Y1, Z1)
%  X1:  stem3 x
%  Y1:  stem3 y
%  Z1:  stem3 z

%  Auto-generated by MATLAB on 14-Apr-2019 02:51:35

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create stem3
stem3(X1,Y1,Z1,'MarkerFaceColor',[1 0 1],'Color',[0 0 0]);

% Create xlabel
xlabel('n');

view(axes1,[-37.5 30]);
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'Color',[0.972549021244049 0.972549021244049 0.972549021244049]);
